version: '3'
services:
  epgstation:
    build: build
    volumes:
      - ./config/:/opt/EPGStation/config
      - ./recorded:/opt/EPGStation/recorded
    ports:
      - 8888:8888
    restart: always
